lerna.json, packages/contenttype-commonmark/package.json, packages/contenttype-html/package.json, packages/core/package.json, packages/hir/package.json, packages/renderer-commonmark/package.json, packages/renderer-hir/package.json, packages/renderer-plain-text/package.json, packages/renderer-react/package.json
The renderers weren't including atjson/renderer-hir in their standard deps. Fix this, and incr versions.
=> Fix dependencies

packages/source-commonmark/test/__snapshots__/commonmark-spec-test.ts.snap, packages/source-commonmark/test/commonmark-spec-test.ts, packages/source-commonmark/test/commonmark-test.ts
I'm going to embark on refactoring `@atjson/source-html` and `@atjson/source-commonmark`, so these snapshots will make it much easier when refactoring to find out what structural things I've changed (it should be none other than annotation names).
In addition, I've gone and skipped the tests that we aren't going to fix at the moment with comments on why each of the tests is failing.
=> Snapshot commonmark spec

packages/source-gdocs-paste/src/gdocs-parser.ts, packages/source-gdocs-paste/src/index.ts, packages/source-gdocs-paste/src/link-styles.ts, packages/source-gdocs-paste/src/list-styles.ts, packages/source-gdocs-paste/src/schema.ts, packages/source-gdocs-paste/src/text-styles.ts, packages/source-gdocs-paste/test/atjson-source-gdocs-paste-test.ts, packages/source-gdocs-paste/test/atjson-source-gdocs-translator-test.ts
This is minimal, but adds support for links from Google Docs pasted docs.
=> Add support for links from Google Docs paste buffers

packages/document/src/query.ts, packages/document/test/query-test.ts, packages/source-html/src/index.ts, packages/source-html/src/schema.ts, packages/source-html/src/translator.ts, packages/source-html/test/source-html-test.ts
This adds a prefix to all imported HTML so it has a prefix of `-html-`
=> Add namespacing to HTML source (and tests!)

packages/@atjson/conventional-changelog-emoji/CHANGELOG.md, packages/@atjson/document/CHANGELOG.md, packages/@atjson/editor/CHANGELOG.md, packages/@atjson/hir/CHANGELOG.md, packages/@atjson/renderer-commonmark/CHANGELOG.md, packages/@atjson/renderer-graphviz/CHANGELOG.md, packages/@atjson/renderer-hir/CHANGELOG.md, packages/@atjson/renderer-plain-text/CHANGELOG.md, packages/@atjson/renderer-react/CHANGELOG.md, packages/@atjson/schema/CHANGELOG.md, packages/@atjson/source-commonmark/CHANGELOG.md, packages/@atjson/source-gdocs-paste/CHANGELOG.md, packages/@atjson/source-html/CHANGELOG.md
because lerna isn't detecting our preset correctly 😭
=> Fix changelog

packages/@atjson/offset-annotations/src/annotations/caption-source.ts
=> Fix imports

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/src/lib/punctuation.ts
Exports punctuation regexes so we can use them in extending classes
=> 🐝 Export punctuation utils

packages/@atjson/offset-annotations/src/annotations/caption-source.ts
Add a `contentType` to caption source.
=> 🐞 Add contentType to caption source

package-lock.json, packages/@atjson/source-html/src/converter.ts, packages/@atjson/source-html/test/source-html-test.ts
Add conversion of `<s>` elements to strikethrough. This behaves in the same way as `<del>`
=> 🐝: Convert <s> elements to strikethrough

website/package-lock.json, website/package.json
This closes a bunch of renovate PRs in bulk.
=> 📦 update dependencies for website

website/docs/analysis.md, website/docs/converters.md, website/docs/custom-renderer.md, website/docs/document-api.md, website/docs/getting-started.md, website/docs/glossary.md, website/docs/google-docs-explainer.md, website/docs/google-docs-paste.md, website/docs/html-renderer.md, website/docs/html-source.md, website/docs/machine-learning.md, website/docs/markdown-renderer.md, website/docs/markdown-source.md, website/docs/mobiledoc-source.md, website/docs/prior-art.md, website/docs/prism-source.md, website/docs/querying.md, website/docs/react-renderer.md, website/docs/structure.md, website/docs/updating-documents.md, website/docs/url-paste.md, website/package-lock.json, website/package.json, website/sidebars.json, website/src/components/QuickBrownFox.tsx, website/src/components/URLPaste.tsx
This adds some more API documentation for `@atjson/document`.
=> 📚 Add API documentation for @atjson/document

packages/@atjson/editor/CHANGELOG.md, packages/@atjson/editor/package.json, packages/@atjson/offset-inspector/CHANGELOG.md, packages/@atjson/offset-inspector/package.json, packages/@atjson/renderer-commonmark/CHANGELOG.md, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-plain-text/CHANGELOG.md, packages/@atjson/renderer-plain-text/package.json, packages/@atjson/source-commonmark/CHANGELOG.md, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-html/CHANGELOG.md, packages/@atjson/source-html/package.json, packages/@atjson/source-html/src/index.ts, packages/@atjson/source-prism/CHANGELOG.md, packages/@atjson/source-prism/package.json
Exports GlobalAttributes for use when extending the HTMLSource.
New document sources will be able to define annotations which include these attributes which will be useful for creating custom HTML elements.
=> 🐞: Export global attrs for extending HTMLSource

packages/@atjson/source-html/src/converter/third-party-embeds.ts, packages/@atjson/source-html/test/converter-test.ts
Follow up to #367 per @bachbui's comments :)
=> Ahh, be more correct around checking the Ceros script tag

.github/workflows/ci.yml, commitlint.config.js, lerna.json, package-lock.json, package.json, renovate.json
This has become a bit of a pain point for developers working in the repository and correctly identifying features / fixes / etc.
The goal of the emojis was to be more accessible for folks who aren't primarily devs full-time, or come from a non-technical background. It didn't succeed at achieving those goals, and we can make the repository more accessible in places where it counts more: documentation and tools!
=> 👋 bye conventional-changelog-emoji

packages/@atjson/document/src/index.ts, packages/@atjson/document/src/internals.ts, packages/@atjson/document/src/utils.ts, packages/@atjson/document/test/annotation-test.ts, packages/@atjson/hir/src/hir-node.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/source-commonmark/test/extensions-test.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/test/source-test.ts
I'm opening the pull request to verify the performance characteristics of https://github.com/CondeNast/atjson/projects/1#card-30451883
If this works well, this will fix https://github.com/CondeNast/atjson/issues/380
=> feat: add Annotation is type narrowing function

packages/@atjson/source-ckeditor/src/source.ts, packages/@atjson/source-ckeditor/test/source-classic-build-test.ts
This will help infer nesting hierarchy
=> fix: update children start/end positions in source-ckeditor

packages/@atjson/source-ckeditor/src/index.ts
Want to use some of the functions from there in cn-ck
=> chore: export utils from source-ck

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/offset-annotations/test/social-urls-test.ts
Add support for identifying megaphone playlist and episode URLs
=> feat: identify megaphone playlist/episode URLs

packages/@atjson/offset-annotations/src/annotations/link.ts
This adds the isAffiliateLInk to offset-annotations
=> feat: add affiliate link attribute

packages/@atjson/offset-annotations/src/annotations/link.ts
Update isAffiliateLink to use boolean vs string
=> feat: update code to use boolean instead of string

packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts, packages/@atjson/source-html/test/converter-test.ts
Ticket: [atc-2796](https://cnissues.atlassian.net/browse/ATC-2796)
Add wirewax embed link support to the video embed modal
=> feat(video-embed): support wirewax urls

packages/@atjson/offset-annotations/package.json, packages/@atjson/offset-annotations/src/annotations/ceros-embed.ts
Added size attribute " cerosEmbedStyle " to the ceros-embed annotation
=> fix(ceros-embed): adding size attribute to annotation

package-lock.json, packages/@atjson/offset-annotations/CHANGELOG.md, packages/@atjson/offset-annotations/package.json, packages/@atjson/source-wordpress-shortcode/CHANGELOG.md, packages/@atjson/source-wordpress-shortcode/package.json
Fix versions in the package.json files to do a clean release
=> Release 0.40.0

CONTRIBUTING.md
The Lerna link no longer exists, updated the link.
=> broken link in CONTRIBUTING.md

packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize-test.ts, packages/@atjson/source-html/test/converter-test.ts, packages/@atjson/source-prism/test/__snapshots__/prism-test.ts.snap
Extracted from #1452, this fixes an issue with serialization where jagged blocks within nested blocks weren't being serialized correctly. This fixes that, which updates a bunch of HTML serializations to include text properly.
(This would've been caught previously if we had round-trip tests for HTML)
=> Fix serializing jagged lists

.github/workflows/ci.yml, .github/workflows/perf.yml, perf-kit/anonymize-fixtures.ts, perf-kit/fixtures/index.ts, perf-kit/index.ts
Before merging #1483, I'd like to split up this bit that adds performance profile info more visibly to the commit status.
This will give us some clearer ideas about performance benefits that will give better hints to developers without having to dig into the performance profile results.
=> Add HTML performance profiles

packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer-test.tsx, website/docs/react-renderer.mdx, website/src/components/QuickBrownFox.tsx, website/src/components/URLPaste.tsx
Splat children correctly and set Default components where necessary. 😭 forgot that this was changed 😭
=> fix: handle children properly in fragments

packages/@atjson/offset-annotations/src/annotations/threads-embed.ts
I forgot to add this property to the threads-embed 😭
=> chore: add layout to threads-embed

packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation.test.ts
This adds support for expanding YouTube Shorts into embeds automatically on paste.
=> feat: add support for YouTube Shorts

packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer.test.tsx
brings `@atjson/renderer-react` into parity with `@atjson/react`
=> fix: add useDataSet hook to renderer-react

tests/fixtures/html/bluesky.html, tests/fixtures/html/instagram-with-caption.html, tests/fixtures/html/instagram-without-caption.html, tests/fixtures/html/mastodon.html, tests/fixtures/html/reddit.html, tests/fixtures/html/threads.html, tests/fixtures/html/tiktok.html, tests/fixtures/html/twitter.html, tests/html-round-trip.test.ts
I'm adding more fixtures for HTML round trip tests to ensure that we are maintaining coverage :)
=> chore: add more fixtures for html round trip
