CondeNast/atjson

packages/hir/src/hir-node.ts, packages/hir/src/hir.ts, packages/hir/test/hir-test.ts
The test case written for this will fail under current conditions. In the current codebase (with the paragraph case removed), the structure of this will look like:
```json
{
"type": "root", 
"children": [{
"type": "paragraph",
"children": ["One fish"],
}, {
"type": "paragraph",
"children": [
"Two fish",
{
"type": "paragraph",
"children": []
}
],
}, {
"type": "paragraph",
"children": ["Red fish"],
}, {
"type": "paragraph",
"children": ["Blue fish"],
}]
}
```
The naïve solution that I introduced previously will introduce the paragraph after the paragraph it was supposed to come before:
```json
{
"type": "root", 
"children": [{
"type": "paragraph",
"children": ["One fish"],
}, {
"type": "paragraph",
"children": ["Two fish"],
}, {
"type": "paragraph",
"children": ["Red fish"],
}, {
"type": …
```
=> Fix nested paragraphs

packages/document/src/index.ts, packages/document/src/query.ts, packages/document/test/query-test.ts
This adds an imperative API for documents that allows us to change historical and future annotations added to the document.
I've designed this to make code for sources easier to use. My thoughts on this are that this api will remove the need for a canonical format, allowing for simple transformations between types of annotations.
A common example of this is using the HTML source. We'd like to map HTML elements to annotations that the commonmark renderer can understand. Using this API, we'd be able to update headings for rendering:
```js
import HTMLSource from '@atjson/source-html';
let document = new HTMLSource('<h1>Hello</h1>').toAtJSON();
document.where({ type: 'h1' }).set({ type: 'heading', attributes: { level: 1 }).done();
```
Note: I'd like to remove the `done` at the end of the …
=> Add imperative for transforming annotations on a document

packages/document/src/index.ts, packages/document/src/query.ts, packages/document/test/query-test.ts
This is useful when an annotation needs to be expanded into multiple annotations. for example, when getting an annotation for `code` from commonmark, we'd like to expand it to a `pre` and `code` annotation.
At some point we will probably find an approach to take multiple annotations and distill them into a single one
=> Allow for map() to return multiple values, allowing for multiplexing

packages/document/src/annotation.ts, packages/document/src/index.ts, packages/document/src/schema.ts, packages/hir/src/hir-node.ts, packages/hir/src/hir.ts, packages/hir/test/hir-node-test.ts, packages/hir/test/hir-test.ts, packages/hir/test/schema.ts, packages/hir/test/utils.ts, packages/renderer-commonmark/test/schema.ts, packages/schema/index.ts, packages/schema/package.json, packages/source-html/src/index.ts, packages/source-html/src/schema.ts
This is the core document schema for an AtJSON document. We're using this as the base specification for what annotations are available from a simple document.
=> Document Schema

README.md
I believe the original travis hooks may have broken when making the repo public. I've updated this repo to use travis-ci.org
=> Update travis badge for travis-ci.org

packages/source-gdocs-paste/LICENSE, packages/source-gdocs-paste/README.md, packages/source-gdocs-paste/content-documentation.md, packages/source-gdocs-paste/package.json, packages/source-gdocs-paste/src/index.ts, packages/source-gdocs-paste/src/list-styles.ts, packages/source-gdocs-paste/src/paragraph-styles.ts, packages/source-gdocs-paste/src/text-styles.ts, packages/source-gdocs-paste/test/__snapshots__/atjson-source-gdocs-paste-test.ts.snap, packages/source-gdocs-paste/test/atjson-source-gdocs-paste-test.ts, packages/source-gdocs-paste/test/fixtures/complex.json, packages/source-gdocs-paste/tsconfig.json
This is a prototype source to support copy/paste with minimal formatting preserved from Google Docs.
Todo:
n.b. that the goal of this is _not_ to have a very high-fidelity representation, so we will drop lots of formatting from Google Docs (e.g., fonts, font sizing, font colors, etc, etc).
=> Google Docs (paste) Source, WIP

packages/source-commonmark/src/index.ts
This is to support derived Commonmark parsers (eg copilot-atjson/source-them) being a little bit DRYer and to keep implementations a bit more opinionated. Currently, in order to swap out the parser (i.e., from base MarkdownIt to our cfm parser), it requires re-implementing the constructor.
It's a bit unfortunate that `super()` needs to be called before `this` is available in the constructor, but I don't see an easy way around that (without moving the parse step to a separate method, of course).
=> Make base CommonmarkSource extensible.

packages/source-gdocs-paste/src/gdocs-parser.ts, packages/source-gdocs-paste/src/index.ts, packages/source-gdocs-paste/src/list-styles.ts, packages/source-gdocs-paste/src/paragraph-styles.ts, packages/source-gdocs-paste/src/schema.ts, packages/source-gdocs-paste/src/text-styles.ts, packages/source-gdocs-paste/test/atjson-source-gdocs-paste-test.ts, packages/source-gdocs-paste/test/atjson-source-gdocs-translator-test.ts
Move gdocs source into better alignment with current sources, use -gdocs- prefixes, and add a toCommonSchema translator
=> Some tweaks to improve the gdocs source

packages/renderer-commonmark/src/index.ts, packages/renderer-commonmark/test/commonmark-test.ts
This refactors renderer-commonmark to use HIRNodes directly so we have more context about what children / parents / sibling nodes are for annotations.
It's a bit messier, but it's fortunately a bit less opaque, since all the code lives in the file.
=> Fix ambiguous bold italic

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Some of our editors were encountering issues where formatting would appear in their article, which would appear like:
```md
some sentence. ****
**&nbsp;**
**The actual thing that's bold**
```
It looks like this in markdown:
We would like it to look like:
```md
some sentence.
&nbsp;
**The actual thing that's bold**
```
=> Fix markup around non-breaking spaces and unicode whitespace characters

README.md
I forgot what it stood for and noticed this typo while checking.
I've also defined HIR in the [Condé Dictionary](https://docs.google.com/spreadsheets/d/1UJGlwOXRCh2ciRbTFS7G2IelqfADaSVs0AgzplGcCEU).
=> Fix typo in HIR package doc

LICENSE
This update the license file to be the one that github autogenerates. This will give us a license in the corner, which makes it easier for people to know, at a glance, what license the project has.
=> Update license file so Github shows this as Apache 2.0

packages/@atjson/hir/src/hir-node.ts, packages/@atjson/hir/test/hir-node-test.ts, packages/@atjson/hir/test/hir-test.ts, packages/@atjson/hir/test/schema.ts, packages/@atjson/hir/test/utils.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/__snapshots__/commonmark-spec-test.ts.snap, packages/@atjson/renderer-commonmark/test/commonmark-spec-test.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-html/test/source-html-test.ts
This feature allows for better serialization of our hierarchical intermediate representation as well as some better developer ergonomics.
So, before, to render a sub-document:
```ts
import CommonMarkRenderer, { Annotation } from '@atjson/renderer-commonmark';
export default class extends CommonMarkRenderer {
*figure(node: Annotation): Iterable<any> {
return `![node.description](node.url)|||${this.render(node.caption)}|||`
}
}
```
After, this becomes:
```ts
import CommonMarkRenderer, { Annotation } from '@atjson/renderer-commonmark';
export default class extends CommonMarkRenderer {
*figure(node: Annotation): Iterable<any> {
return `![node.description](node.url)|||${node.caption}|||`
}
}
```
=> Recursively render sub-documents that are attributes

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/src/index.ts, packages/@atjson/source-commonmark/test/commonmark-test.ts
Narrow no-break spaces `U+202F` results in a blank paragraph from Markdown-It. Some of our brands use this to generate extra spacing between paragraphs.
=> Fix empty paragraphs created by narrow no-break space

packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Leading whitespace from Google Docs, for example, was turning paragraphs into code blocks 😭 
This removes leading and trailing (non-significant) whitespace from paragraphs.
=> Fix leading whitespace and tabs turning into code blocks

package.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/attributes.ts, packages/@atjson/document/src/block-annotation.ts, packages/@atjson/document/src/change.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/src/inline-annotation.ts, packages/@atjson/document/src/json.ts, packages/@atjson/document/src/object-annotation.ts, packages/@atjson/document/src/parse-annotation.ts, packages/@atjson/document/src/schema.ts, packages/@atjson/document/test/atjson-insert-test.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/document/test/query-test.ts, packages/@atjson/document/test/test-source.ts, packages/@atjson/document/test/text-source-test.ts, packages/@atjson/editor/package.json
This work makes it possible for us to richly extend our annotation model, enabling us to write a rich text editor (see the `editor` package). Specifically, annotations like `paragraph`, `blockquote`, and `list` require special behavior when newlines are inserted into the document.
To do this in a flexible / extensible way, we need to encode this behavior into classes instead of colocating the logic into the root document.
The highlight of changes is:
1️⃣ The `schema` is a list of annotations to use to hydrate JSON passed into the document.
2️⃣ Annotations at rest now require vendor prefixes to by hydrated correctly. This is done to ensure that we do not have collisions between annotations with the same name. (cf. a Markdown `blockquote` to a HTML `blockquote`)
3️⃣ `attributes` are …
=> Make Annotations classes instead of JS objects

packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/annotations/block.ts, packages/@atjson/document/src/annotations/index.ts, packages/@atjson/document/src/annotations/inline.ts, packages/@atjson/document/src/annotations/object.ts, packages/@atjson/document/src/annotations/parse.ts, packages/@atjson/document/src/annotations/unknown.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/atjson-insert-test.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/document/test/query-test.ts
This adds formal support for unknown annotations.
Unknown Annotations have a particular way of being created; they stuff their `type` and `attributes` into the `attributes`. This means all data is retained for these annotations, while they appear as a homogenous blob. When rendered, these annotations will get categorized into a single bucket of `unknown`, so they can be rendered for debugging purposes in a document.
For an example, if we import the following HTML document into AtJSON,
```html
<p>Hello, <em>world</em>!</p>
```
The document created would be a bunch of Unknown Annotations:
```json
{
"contentType": "application/vnd.atjson+html",
"content": "<p>Hello, <em>world</em>!</p>",
"schema": [],
"annotations": [{
"type": "-atjson-unknown",
"start": 0,
"end": 29,
"attributes": {
"type": …
```
=> Unknown Annotations

packages/@atjson/document/src/attributes.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/src/query.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/document/test/query-test.ts
This PR makes the `where` syntax work again (and the tests!)
A couple of things here:
☝️ There's a bugfix here for annotations that weren't being unprefixed and cloned correctly. (I was using the collection object in the reducer instead of the original attributes object)
✌️ All annotations will undergo a structured clone when being sent through our query language.
Unfortunately, this removes the feature of having a sub-documents in annotations, but that will have to be fixed soon 😢
=> Fix querying to work with Annotation classes

packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts
This PR changes the rendering API so annotation classes can be reused in the render hooks.
Previously, when an annotation was rendered, it would be called with the attributes, that stripped all type information:
```ts
import Renderer from '@atjson/renderer-hir';
import { HIRNode } from '@atjson/hir';
export default class TestRenderer extends Renderer {
*image(attrs: any): IterableIterator<any> {
return `![${attrs.description}](${attrs.src})`;
}
}
```
Now, classes can be reused:
```ts
import { ObjectAnnotation } from '@atjson/document';
import Renderer from '@atjson/renderer-hir';
class Image extends ObjectAnnotation {
static vendorPrefix = 'test';
static type = 'image';
attributes!: {
description: string;
src: string;
};
}
export default class TestRenderer extends Renderer {
*image(image: …
```
=> 🎨 Fix rendering API to handle annotation classes

packages/@atjson/document/src/index.ts
It seems that wherever this package is [imported](https://github.com/CondeNast-Copilot/atjson/blob/130233e43868ead7045e0d69caebecfdc15bfb8c/packages/%40atjson/editor/src/index.ts#L2), it's being referred to as `Document`.
The TypeScript compiler, however, will reveal it as type `AtJSON`, which IMHO is confusing.
This PR changes the class name to `Document`.
Also, consider changing the name to `AtJSONDocument` to be extra explicit...
=> 🛀 @atjson/document: Change default class name from AtJSON to Document.

packages/@atjson/renderer-react/test/react-renderer-test.tsx, packages/@atjson/source-commonmark/src/index.ts, packages/@atjson/source-html/test/source-html-test.ts
Small syntax fixes in packages/@atjson/renderer-react/test/react-renderer-test.tsx and packages/@atjson/source-html/test/source-html-test.ts
=> source-commonmark: Explicitly declare Document as toCommonSchema() return type.

lerna.json, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-plain-text/package.json, packages/@atjson/renderer-react/package.json, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-html/package.json
The `npm publish` has already occurred; but, when npm Git tagged the version and tried to push, the _protected branch hook declined_ prevented it.
=> Publish npm version v0.8.5.

packages/@atjson/editor/package.json, packages/@atjson/hir/package.json, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-graphviz/package.json, packages/@atjson/renderer-hir/package.json, packages/@atjson/renderer-plain-text/package.json, packages/@atjson/renderer-react/package.json, packages/@atjson/schema/package.json, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-gdocs-paste/package.json, packages/@atjson/source-html/package.json
Pinning dependencies will prevent subsequent installs of the same package from installing newer (possibly incompatible) minor versions of dependencies.
We ran into this problem deploying atjson as a dependency-of-a-dependency where our application received a newer version of an atjson dependency than expected when we built and deployed our application, causing rendering to fail on a couple of documents.
=> Pin all internal package dependencies

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-hir/src/index.ts
This allows sub-documents to be rendererd using different renderers instead of itself.
We have some mixed result formats that we're using this for and need to render to a different output format.
=> ✨  allow a HIR to be passed to a renderer

packages/@atjson/document/src/index.ts, packages/@atjson/document/src/query.ts, packages/@atjson/document/test/query-test.ts, packages/@atjson/source-html/src/index.ts, packages/@atjson/source-html/src/translator.ts
There are some changes that will cause some typescript headaches (see the source-html translator) if you've used raw `map`s in the brand mappers, but otherwise this should be transparent and compatible.
We'll need to write up some documentation, but for now it's probably best to look at the examples in the `query-test.js` file in the `document` package.
I also have the intent to move to having Transforms use a proxy to mutate the document to avoid having to duplicate the effort of maintaining annotation lists, but it got to be too much (the `TransformResult` interface can't do it as-is because text changes and ordering matter, and it doesn't account for those, so it's relegated for the moment to handling changes to the AnnotationCollection for chaining purposes).
Please let me know if the …
=> Define Nested Querying

lerna.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Because we support rendering to markdown, we had been escaping special characters used by markdown in case the text itself might contain a markdown sequence. We had been doing this rather aggressively, escaping many common punctuation characters, and instead we can be more targeted with the escaped sequences: for example, looking for `-` where it would indicate a list rather than in all occurrences. 
- Don't escape common punctuation chars: `(),'"?@-$%`
- Also updates lerna version in lerna.json to match version in package.json
=> Remove common punctuation from escaped chars

packages/@atjson/editor/test/tsconfig.json
This sets a TypeScript compilation context for `ts` files in `test/` allowing VSCode (among other editors) to surface TypeScript errors.
=> 🛀 Add non-emitting tsconfig.json to editor/test.

packages/@atjson/document/package.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/index.ts, packages/@atjson/hir/src/hir-node.ts, packages/@atjson/hir/src/hir.ts, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-commonmark/src/index.ts, packages/@atjson/source-gdocs-paste/package.json, packages/@atjson/source-gdocs-paste/src/horizontal-rule.ts, packages/@atjson/source-gdocs-paste/src/link-styles.ts, packages/@atjson/source-gdocs-paste/src/list-styles.ts, packages/@atjson/source-gdocs-paste/src/paragraph-styles.ts, packages/@atjson/source-gdocs-paste/src/text-styles.ts, packages/@atjson/source-html/package.json, packages/@atjson/source-html/src/index.ts
This eases a constraint, making code that generates lots of annotations smaller by not asking the annotation creator to bring their own ids.
`id` can be overridden, which allows annotations to be saved to a database with a different uuid than one provided by the node `uuid` module.
=> 🔍 make `id` optional, using `uuid` when not provided

packages/@atjson/document/src/annotations/index.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/atjson-insert-test.ts, packages/@atjson/document/test/atjson-test.ts
This opens up the potential for stricter typing with annotation creation, as well as tidying up some code (especially if the annotation is known when being created)
When adding an annotation that is not in the document schema, the annotation will be cast into an `UnknownAnnotation`, which means that the annotation will be added, but not rendered (under normal circumstances)
=> ✨🔮 allow Annotation classes or AnnotationJSON to all Document methods

.vscode/launch.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/collection.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/document/test/converter-test.ts, packages/@atjson/document/test/query-test.ts, packages/@atjson/document/test/test-source.ts, packages/@atjson/document/test/text-source-test.ts, packages/@atjson/editor/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-spec-test.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/renderer-plain-text/test/text-renderer-test.ts, packages/@atjson/source-commonmark/src/converter.ts, packages/@atjson/source-commonmark/src/source.ts, packages/@atjson/source-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/test/extensions-test.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/src/source.ts, packages/@atjson/source-gdocs-paste/test/converter-test.ts, packages/@atjson/source-gdocs-paste/test/source-test.ts, packages/@atjson/source-html/src/converter.ts, packages/@atjson/source-html/src/source.ts, packages/@atjson/source-html/test/source-html-test.ts, packages/@atjson/source-mobiledoc/src/converter.ts, packages/@atjson/source-mobiledoc/src/source.ts, packages/@atjson/source-mobiledoc/test/source-mobiledoc-test.ts
This adds coercion to documents when converting between sources.
By adding this feature, multiple passes can be made to incrementally convert to a final source.
A use case is converting Github markdown to the Offset source. The Github markdown is an extension of the Commonmark source that AtJSON has built in. It adds a few other features. To convert from Github markdown to Offset, the following code will do the trick:
```js
class GithubMarkdownSource extends CommonmarkSource {
static contentType = 'application/vnd.atjson+gfm';
static schema = [...CommonmarkSource.schema, Strikethrough, TaskListItem, Table, TableCell, TableRow];
static markdownParser() {
return markdownIt('gfm');
}
}
GithubMarkdownSource.defineConverterTo(OffsetSource, doc => {
doc.where({ type: '-github-strikethrough' …
```
=> Coerce or convert to sources

packages/@atjson/document/src/annotation.ts, packages/@atjson/source-gdocs-paste/README.md, packages/@atjson/source-gdocs-paste/package.json, packages/@atjson/source-gdocs-paste/public/app.ts, packages/@atjson/source-gdocs-paste/public/index.html, packages/@atjson/source-gdocs-paste/public/style.scss, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/src/link-styles.ts, packages/@atjson/source-gdocs-paste/src/text-styles.ts, packages/@atjson/source-gdocs-paste/test/converter-test.ts, packages/@atjson/source-gdocs-paste/test/fixtures/partial.json, packages/@atjson/source-gdocs-paste/test/fixtures/underline.json, packages/@atjson/source-gdocs-paste/test/source-test.ts, packages/@atjson/source-gdocs-paste/tsconfig.json
When pasting from a GDocs document, the annotations don't get closed until the character _after_ the style is done. This means that after we loop through all of the styles, we need to close any that are
currently open to retain the intended paste.
=> 🐛 Close any open annotations from Google Docs paste

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
We've had some complaints from our editors about getting unnecessary escape sequences showing up in markdown that impede their ability to copyedit text pasted from Google Docs.
This change limits occurrences of markdown escape sequences for [sic] and numbers that include periods.
=> Remove more escape sequences

packages/@atjson/source-commonmark/src/parser.ts
Our custom markdown extension adds metadata to the closing token of a custom markdown-it extension, so we need to pass that into the content handler
=> 🐞 Pass closing token in addition to the opening token

packages/@atjson/source-prism/package.json
Quick fix to include source-html in the dependencies list for the prism source.
=> 🐝: Include `source-html` in dependencies list

packages/@atjson/offset-inspector/src/index.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-spec-test.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/renderer-graphviz/src/index.ts, packages/@atjson/renderer-graphviz/test/graphviz-test.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts, packages/@atjson/renderer-plain-text/test/text-renderer-test.ts, packages/@atjson/source-commonmark/test/utils.ts, packages/@atjson/source-prism/public/app.js, packages/@atjson/source-url/test/url-test.ts
This updates the base hir renderer to have a static render method,
so inheriting renderers are updated to follow suit.
This also adds the `document` to the hir renderer `Context` interface,
so that we have access to the source document while rendering out
annotations, which may be necessary if that rendering depends on
text that is unrelated to the hir tree.
=> Make Renderer.render a static method

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/src/lib/punctuation.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
See https://spec.commonmark.org/0.28/#delimiter-run
Markdown requires that a left-flanking delimiter run (ie, one that opens
emphasis) must:
- Not be followed by whitespace
- Be preceded by whitespace or punctuation if followed by punctuation
Similarly a right-flanking delimiter run (ie, one that closes emphasis)
must:
- Not be preceded by whitespace
- Be followed by whitespace or punctuation if preceded by punctuation
We were already correctly pushing boundary whitespace out of emphasized
text. This fix addresses the second requirements by checking if the
text immediately inside the boundary is punctuation and if the text
immediately outside is not whitespace or punctuation, and pushing the
punctuation outside the boundary in that case.
Example:
The markdown sequence `normal_-italic_` is …
=> 🐝: Fix bug for rendering invalid delimiter runs

packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/test/converter-test.ts
Title/Subtitle GDocs annotations should be considered non-body
annotations and aren't supported in Offset (yet).
=> 🐜 Fix converter to offset to remove (Sub)Titles

packages/@atjson/document/src/index.ts
Allows documents to accept either AnnotationJSON or Annotation class instances in its constructor.
=> 🐝 Allow annotation classes in document constructor

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-hir/README.md, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts
This adds a nicety to the HIR renderer so you can use the classified version of the `type` (it also enforces a lowercase convention that @blaine and I discussed briefly)
=> 🍢✨ Allow using classified names for rendering hooks (`Bold` & `bold` / `GiphyEmbed` & `giphy-embed`)

.travis.yml, package-lock.json, package.json, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-commonmark/performance/README.md, packages/@atjson/renderer-commonmark/performance/index.js
This adds a performance testing to `renderer-commonmark` so we have a baseline for round-trip conversions and alterations to markdown.
I'm also horrible at statistics, so I *hope* what I wrote is correct 😓
=> ⏱add performance stats to renderer-commonmark

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/src/lib/punctuation.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/src/parser.ts
Only split on delimiters for Bold and Italic and include whitespace 
at paragraph boundaries. This helps fix delimiter run parsing by having 
parse annotations over a newline character rather than an object 
replacement character so that delimiter runs can 'see' that there is 
whitespace at the boundary
=> 🐝 Boundary delimiter fix

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/src/parser.ts
🐝 Better fix for delimiter runs  …
Instead of looking for & skipping over ORCs when looking for adjacent
characters, skip over ParseAnnotations.
When checking the adjacent character, we can preserve boundary
punctuation if a non-parse annotation begins or ends in the region
between the boundary punctuation and the adjacent character, as that
annotation will insert either a new line or other punctuation character
between them
🐝 Revert previous change in favor of better fix
=> Better delimiter fix

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
When escaping text that looks like a markdown ordered list, we want to
preserve leading whitespace. This fixes a bug where a sentence ending
with an italic and then a number would have the space between them
removed, as the end of the sentence is rendered as text but looks like
ordered list markdown:
`Ending with *italic* 1. ` -> `Ending with *italic*1\.`
We still have to escape the terminal period, but now it will render as
`Ending with *italic* 1. ` -> `Ending with *italic* 1\.` with the space
preserved.
=> 🐝 Preserve space before sentence-terminating number

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Fixes bug with trailing whitespace detection in the `split()` function
=>  🐝 Fix bug related to whitespace export refactor

packages/@atjson/document/src/index.ts, packages/@atjson/document/test/atjson-test.ts
I found this bug upstream in our Condé extensions to AtJSON; this should fix bugs that popped up there.
=> 🐛 Reify unknown annotations when passing them into `createAnnotation`

package-lock.json, package.json, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/offset-core-components/src/mixins/component.ts, packages/@atjson/offset-inspector/src/document-inspector/annotations-inspector.ts, packages/@atjson/source-url/test/url-test.ts, typedoc.js
`slice` was previously returning 0 length annotations in the results, which caused issues when rendering out. It makes sense to not include them in the sliced document.
=> 🐝 fix slice so it only includes overlapping annotations from the parent document

package-lock.json, package.json, packages/@atjson/editor/package.json, packages/@atjson/offset-core-components/package.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/src/lib/punctuation.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-react/src/index.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-mobiledoc/src/parser.ts, packages/@atjson/source-prism/src/source.ts, packages/@atjson/source-url/src/converter.ts
This PR does a few things:
- 📦 Updates packages for TSLint / TypeScript
- 💆‍♂️ Fixes errors reported by TSLint
- 💻 Makes type inference better with `Renderer.render` to infer the params from the renderer constructor.
=> Fix TSLint errors and improve type inference

packages/@atjson/offset-annotations/src/annotations/iframe-embed.ts
This adds the `sandbox` property to the `iframe-embed`. This attribute is intended to map directly to the optional `Iframe` [sandbox attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox).
-----
🗒 I read the [CONTRIBUTING](https://github.com/CondeNast-Copilot/atjson/blob/latest/CONTRIBUTING.md) docs and have done my best to follow along. I couldn't figure out the whole conventional commit _emoji_, so I tried to at least follow the typical pattern. I can amend the message as desired.
This attribute does not appear to have corresponding tests and I'm not sure how to best contribute in that regard.
=> feat: add sandbox to iframe-embed attributes

package-lock.json, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/converter-test.ts, packages/@atjson/source-commonmark/test/extensions-test.ts, packages/@atjson/source-prism/src/converter.ts
🚨 When converting a document, it will no longer coerce a document. You will need to do this yourself!
🚨 You can no longer nest converters inside of another converter. Instead import `getConverterFor` from @atjson/document and use the function supplied from that.
These improvements are designed to improve the developer experience of atjson for developers. We've encountered some frustrations where:
1. Conversions wouldn't run because there are two different versions of @atjson/document installed.
📝 If you are using atjson, update your dependencies to this version. Any version increment after this shouldn't break your converters.
2. Converters would get called, but the document was made up of only UnknownAnnotations.
👩🏽‍🏫 You're no longer allowed to nest converters. This change was done to …
=> ✨ Reduce magic in converting documents.

.travis.yml, CONTRIBUTING.md, README.md, packages/@atjson/conventional-changelog-emoji/CHANGELOG.md, packages/@atjson/conventional-changelog-emoji/README.md, packages/@atjson/document/CHANGELOG.md, packages/@atjson/editor/CHANGELOG.md, packages/@atjson/hir/CHANGELOG.md, packages/@atjson/hir/package.json, packages/@atjson/offset-annotations/CHANGELOG.md, packages/@atjson/offset-core-components/CHANGELOG.md, packages/@atjson/offset-inspector/CHANGELOG.md, packages/@atjson/renderer-commonmark/CHANGELOG.md, packages/@atjson/renderer-graphviz/CHANGELOG.md, packages/@atjson/renderer-hir/CHANGELOG.md, packages/@atjson/renderer-plain-text/CHANGELOG.md, packages/@atjson/renderer-react/CHANGELOG.md, packages/@atjson/renderer-webcomponent/CHANGELOG.md, packages/@atjson/source-commonmark/CHANGELOG.md, packages/@atjson/source-gdocs-paste/CHANGELOG.md, packages/@atjson/source-html/CHANGELOG.md, packages/@atjson/source-mobiledoc/CHANGELOG.md, packages/@atjson/source-prism/CHANGELOG.md, packages/@atjson/source-url/CHANGELOG.md
Pretty self-explanatory, we had some breaking links in our scripts, READMEs, and CHANGELOGs
=> 🐞 fix references to wrong github repository

packages/@atjson/offset-annotations/src/annotations/blockquote.ts, packages/@atjson/offset-annotations/src/annotations/code.ts, packages/@atjson/offset-annotations/src/annotations/heading.ts, packages/@atjson/offset-annotations/src/annotations/html.ts, packages/@atjson/offset-annotations/src/annotations/iframe-embed.ts, packages/@atjson/offset-annotations/src/annotations/image.ts, packages/@atjson/offset-annotations/src/annotations/link.ts, packages/@atjson/offset-annotations/src/annotations/list.ts, packages/@atjson/renderer-html/.npmignore, packages/@atjson/renderer-html/.npmrc, packages/@atjson/renderer-html/README.md, packages/@atjson/renderer-html/package.json, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/renderer-test.ts, packages/@atjson/renderer-html/tsconfig.json, packages/@atjson/renderer-html/tslint.json, packages/@atjson/source-html/src/converter.ts, packages/@atjson/source-html/test/source-html-test.ts
We're trying to integrate atjson with CKEditor, so this is one of the first steps! We need to have a round-trip renderer from HTML so we can allow our editors to switch between CKEditor and our markdown editor.
This gives us a nice extension point as well (using the `$` function) to add our own renderers when we'll need them. 😄
=> Add HTML renderer for atjson

packages/@atjson/editor/package.json, packages/@atjson/hir/package.json, packages/@atjson/offset-annotations/package.json, packages/@atjson/offset-core-components/package.json, packages/@atjson/offset-inspector/package.json, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-graphviz/package.json, packages/@atjson/renderer-hir/package.json, packages/@atjson/renderer-html/package.json, packages/@atjson/renderer-plain-text/package.json, packages/@atjson/renderer-webcomponent/package.json, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-gdocs-paste/package.json, packages/@atjson/source-html/package.json, packages/@atjson/source-mobiledoc/package.json, packages/@atjson/source-prism/package.json, packages/@atjson/source-url/package.json
This should fix some dependency hell where installs of many sources / renderers result in a borked build.
=> Make @atjson/document a peer dependency instead of a dependency

packages/@atjson/offset-annotations/src/annotations/link.ts
This was causing some typing errors when testing the react renderer.
=> 🐞 make "title" optional on Link annotations

package-lock.json, package.json, packages/@atjson/source-html/src/parser.ts, tsconfig.json
The upgrade to parse5 to `^5.0.0` broke the HTML source because of some changes to the API. This was caused by some cached modules in the tests (it ended up getting cleared, and caused tests to fail).
=> 🐞 Fix parse5 typings and upgrade

packages/@atjson/renderer-html/package.json, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/renderer-test.ts, packages/@atjson/source-html/test/source-html-test.ts
This fixes a bug where we weren't encoding HTML entities or escaping URLs when we were writing a document to HTML.
=> Encode HTML entities when rendering to HTML

website/package-lock.json, website/package.json, website/plugins/docusaurus-typescript-loader/index.js, website/plugins/docusaurus-typescript-loader/package-lock.json, website/plugins/docusaurus-typescript-loader/package.json
This changes us to use the `babel-loader` webpack package and also removes hard-coded references to our packages, instead opting for relative paths.
I've also made it so the `browserslist` property in `package.json` for the website is used (it wasn't because docusaurus doesn't look at any user configuration).
This was resulting in `regeneratorRuntime` errors, which was pretty annoying, and caused documentation not to load.
=> 🐞 fix TypeScript loading in the website

packages/@atjson/source-commonmark/src/annotations/link.ts
Leaving this required has resulted in difficulty using `Document#equals` between HTML sources and commonmark sources.
=> 🐞 make title optional on markdown link annotations

packages/@atjson/document/src/attributes.ts, packages/@atjson/document/test/annotation-test.ts, packages/@atjson/document/test/test-source.ts, packages/@atjson/source-prism/test/__snapshots__/prism-test.ts.snap
This removes undefined values from the JSON when cloning or calling toJSON, which fixes equal-ness between annotations.
This is the _real_ fix for HTML & Markdown sources not creating equivalent annotations.
=> 🐞 `clone` and `toJSON` coerced `undefined` values into `null`

packages/@atjson/document/src/index.ts, packages/@atjson/document/test/converter-test.ts
This prevents converters from modifying e.g ranges on the original document's annotations (see test for a simple example of what this fixes)
=> fix: clone annotations on conversion document

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
This updates the commonmark renderer to use backslash + newline to
represent a line break. This allows for multiple consecutive line breaks
which the old md (space + space + newline) did not.
This also fixes behavior for line breaks ending paragraphs and block
elements, as well as line breaks in code and html blocks.
=> 🐝: fix consecutive line breaks

packages/@atjson/offset-annotations/src/utils/social-urls.ts
Removes an import added by mistake, a result of code autocompletion + carelessness.
=> 🐞: Remove URL import added by mistake

packages/@atjson/hir/src/annotations/text.ts, packages/@atjson/hir/src/hir-node.ts, packages/@atjson/renderer-graphviz/test/graphviz-test.ts, packages/@atjson/source-commonmark/src/annotations/bullet_list.ts, packages/@atjson/source-commonmark/src/annotations/fence.ts, packages/@atjson/source-commonmark/src/annotations/heading.ts, packages/@atjson/source-commonmark/src/annotations/image.ts, packages/@atjson/source-commonmark/src/annotations/link.ts, packages/@atjson/source-commonmark/src/annotations/ordered_list.ts, packages/@atjson/source-gdocs-paste/src/annotations/heading.ts, packages/@atjson/source-gdocs-paste/src/annotations/link.ts, packages/@atjson/source-gdocs-paste/src/annotations/list-item.ts, packages/@atjson/source-gdocs-paste/src/annotations/list.ts, packages/@atjson/source-gdocs-paste/src/annotations/vertical-adjust.ts, packages/@atjson/source-mobiledoc/README.md, packages/@atjson/source-mobiledoc/src/annotations/anchor.ts, packages/@atjson/source-mobiledoc/src/annotations/image.ts, packages/@atjson/source-mobiledoc/src/annotations/ordered-list.ts, packages/@atjson/source-mobiledoc/test/source-mobiledoc-test.ts, website/docs/mobiledoc-source.md
This PR fixes #232 by adding type definitions to annotations or by moving them from `attributes!` to the generic interface on the annotation itself.
=> Fix annotation defs

packages/@atjson/renderer-html/src/index.ts
This changes the signature for the `$` html generator shorthand to remove the `selfClosing` parameter, and fixes #293 
> **NOTE**: This is a breaking change to how we handle attributes; please pass them in directly, since void elements are handled automatically by this API.
=> fix: automatically self-close void elements for the HTML renderer

packages/@atjson/renderer-commonmark/CHANGELOG.md, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/src/lib/punctuation.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/CHANGELOG.md, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-commonmark/test/commonmark-test.ts
This PR updates the Commonmark renderer to support documents containing unicode emspaces (`\u2003`). There are two relevant changes:
When rendering Paragraphs, we were stripping all leading and trailing whitespace characters from their text to prevent the possibility of these characters being interpreted as markdown symbols, as leading spaces might be interpreted as an indented code block and trailing spaces might be interpreted as a line break. We were being overzealous in this stripping, as MD only considers certain whitespace characters as meaningful in this way. We obtained a narrower set of characters to strip by considering the chars which are matched by `[\s]`, `[ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`, and checking which of these are meaningful …
=> Paragraph whitespace

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Update the Commonmark renderer to always entity-escape unicode emspace characters. This is necessary since many md parsers will drop unicode whitespace characters. We previously added this encoding only when the `escapeHtmlEntities` flag was set on the renderer, but this should be done in any case, like we are doing with non-breaking spaces.
=> 🐞Always entity-escape emspaces

packages/@atjson/source-html/src/converter/convertSocialEmbeds.ts, packages/@atjson/source-html/test/source-html-test.ts
This correctly identifies the whole HTML chunk and removes the link and paragraph following the embed. When we were implementing smart embedding and a Giphy integration, we found that embedding full iframe embed codes from Giphy weren't being recognized because of the trailing paragraph.
This feature removes the `via Giphy` text that follows the embed and the paragraph / link that follows, resulting in cleaner output
=> ✨ handle full giphy embeds when converting from HTML

package-lock.json, package.json, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/document-test.ts, performance/document-canonical-perf.js
[Document#canonical](Document#canonical) is a known performance bottleneck for some consuming applications (It's known to take > 500ms in common cases involving e.g markdown text with hundreds of links). Some performance debugging shows that a major problem is memory allocation and GC, which I believed to be due to inefficient string manipulation. Additionally a cursory look at the old implementation shows that it is unnecessarily abstract, deferring a lot of fairly straightforward behavior to method invocations. This reimplementation approaches both of those issues by **aggressively inlining and for-looping as much code as is practical**, and **moving the string manipulation into a series of `+` operator concatenations all within the same function body.**
Rudimentary benchmarks show that …
=> Implement bulk text deletion to improve the performance of Document#canonical

packages/@atjson/document/src/collection.ts, packages/@atjson/document/src/index.ts, packages/@atjson/document/test/document-test.ts, performance/document-canonical-perf.js
This should further improve the performance of `canonical`, including in some cases that weren't particularly affected by the previous change
=> remove call to `where` and add bulk annotation deletion

packages/@atjson/source-html/src/parser.ts, packages/@atjson/source-html/test/source-html-test.ts
This changes the code path for source-html by always going through a full HTML document parse, resulting in quirks-mode for document fragments. The change shouldn't change any behavior, but it allows atjson to ingest full HTML pages.
=> 🐝 fix cases where a full HTML document is passed to source-html

packages/@atjson/document/src/index.ts, packages/@atjson/document/test/document-test.ts
There was a case where `removeAnnotations` would remove all elements from the array argument, which was causing problems in `canonical` because that same array was used as an argument to `deleteTextRanges`
=> Make sure methods like `removeAnnotations` and `deleteTextRanges` don't mutate their argument (more than expected)

packages/@atjson/source-gdocs-paste/src/converter.ts
Moves some inline regexes I saw in the gdocs converter to a const
=> 🛀 Move inline regexes to const

packages/@atjson/document/tsconfig.modules.json, packages/@atjson/hir/tsconfig.modules.json, packages/@atjson/offset-annotations/tsconfig.modules.json, packages/@atjson/renderer-commonmark/tsconfig.modules.json, packages/@atjson/renderer-graphviz/tsconfig.modules.json, packages/@atjson/renderer-hir/tsconfig.modules.json, packages/@atjson/renderer-html/tsconfig.modules.json, packages/@atjson/renderer-plain-text/tsconfig.modules.json, packages/@atjson/renderer-react/tsconfig.modules.json, packages/@atjson/renderer-webcomponent/tsconfig.modules.json, packages/@atjson/source-commonmark/tsconfig.modules.json, packages/@atjson/source-gdocs-paste/tsconfig.modules.json, packages/@atjson/source-html/tsconfig.modules.json, packages/@atjson/source-mobiledoc/tsconfig.modules.json, packages/@atjson/source-prism/tsconfig.modules.json, packages/@atjson/source-url/tsconfig.modules.json
Before:
```js
"data-aspectRatio": embed.attributes.aspectRatio?.toString(),
"data-mobile-aspectRatio": embed.attributes.mobileAspectRatio?.toString()
```
After:
```js
"data-aspectRatio": (_a = embed.attributes.aspectRatio) === null || _a === void 0 ? void 0 : _a.toString(),
"data-mobile-aspectRatio": (_b = embed.attributes.mobileAspectRatio) === null || _b === void 0 ? void 0 : _b.toString()
```
=> 🐛 use ES2018 for modules output because nullish coalescing and optional chaining is breaking upstream webpack builds

packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer-test.tsx, website/docs/react-renderer.md
There a few things going on here that I'm seeking feedback on before moving forward with this approach.
- The component map is no longer passed directly to the `ReactRenderer.render` function but is instead provided via the newly-added `ReactRendererProvider` that you must wrap the `ReactRenderer.render` call with.
- This also allows you to use this Provider in nested subdocuments, allowing you to change the component map within the render tree. I've added a test to demonstrate usage.
- Providing the component map via context also lets us remove all the `componentLookup` aspects of the `ReactRenderer` class, which I've done.
- The `ReactRendererProvider` is not a direct usage of the React context; instead it's a thin wrapper that allows you to pass to a map that gets merged with its …
=> React-renderer: Use React context for component map

packages/@atjson/source-html/src/converter/third-party-embeds.ts, packages/@atjson/source-html/test/converter-test.ts
When implementing a paste handler, I was encountering some "unknown" annotations leaking through due to the ceros code not having the `data-ceros-origin-domains` data attribute.
This change relaxes the matching requirements and instead looks for the script to have `view.ceros.com` in the script tag (I know that this is not fully correct, but I think it's ok in this circumstance).
=> 🐛 don't look for data-ceros-origin-domains when parsing ceros embeds

__mocks__/uuid-random.js, __mocks__/uuid.js, package-lock.json, package.json, packages/@atjson/document/package.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/hir/package.json
I was seeing some minor garbage collections that I tracked down to allocations in node-uuid. Swapping out this library for uuid-random which has better benchmarks improved performance reliably in the degenerate markdown cases.
=> 🚀 Use a more performant uuid library

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/source-url/src/converter.ts, packages/@atjson/source-url/test/url-test.ts
This enables identifying Spotify urls in our SocialURLs util, which allows the URL source to convert raw spotify urls to IframeEmbeds. This also extends `SocialURLs.identify` to include extra attributes in the identification which are used here to set the height and width of the Spotify player:
`https://open.spotify.com/[?embed/][:type]/[:id]` ->
`<iframe src="https://open.spotify.com/embed/[:type]/[:id]" width="300" height="[380 or 80]"></iframe>`
=> Spotify urls

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/source-html/src/converter/social-embeds.ts, packages/@atjson/source-url/src/converter.ts
This also creates a more discrete union so we can have stronger type assertions
about whether attributes / Class exists on the result of the identify call.
=> chore: refactor SocialURLs code to return a normalized attributes object

packages/@atjson/offset-annotations/src/utils/aspect-ratios.ts, packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/aspect-ratio-test.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts
I found a bug where `searchParams` wasn't being included when canonicalizing a URL 😭
=> fix: add tests and fix a bug where searchParams were being removed

packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-plain-text/src/index.ts, packages/@atjson/source-url/src/converter.ts
This adds checks to the HIR Renderer to ensure that rendering fails with UnknownAnnotations present in the document. In the event that any _known_ annotations are present in the document and not handled in a given renderer, a warning will be thrown on the debug console.
I've added tslint ignores for the console lines; I'm not sure this is the best thing to do, but I'm not sure any other way to surface the relevant warnings. I can't think of any environment where `console` is absent, but maybe we should add a guard around that, just in case?
=> Just say no to Unknown-Unknowns!

packages/@atjson/source-html/src/converter/video-embeds.ts, packages/@atjson/source-html/test/converter-test.ts
We have received some reports of iframes being pasted into our rich text editor that were failing to show up because of a protocol-relative URL.
This change fixes that issue and adds tests for them.
=> fix: protocol-relative iframes were throwing errors when being converted

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/offset-annotations/test/social-urls-test.ts, packages/@atjson/source-html/test/converter-test.ts
Add the ability to identify Spotify podcast embeds. The sizing info was pulled from a Spotify podcast episode embed code:
```
<iframe src="https://open.spotify.com/embed-podcast/episode/056ZfewzAOQFphcDjva5bP" width="100%" height="232" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
```
<iframe src="https://open.spotify.com/embed-podcast/show/1iohmBNlRooIVtukKeavRa" width="100%" height="232" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
=> chore: enable identifying spotify podcasts

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-plain-text/src/index.ts, packages/@atjson/renderer-react/src/index.ts
This was causing issues when trying to upgrade upstream dependencies to TypeScript 3.8.
=> chore: remove unnecessary return types

.github/workflows/ci.yml
I've installed [commitlint](https://github.com/apps/commitlint/) on atjson to help with writing correct commit messages
=> chore: use commitlint bot instead of github action

packages/@atjson/hir/package.json, packages/@atjson/offset-annotations/package.json, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-graphviz/package.json, packages/@atjson/renderer-hir/package.json, packages/@atjson/renderer-html/package.json, packages/@atjson/renderer-plain-text/package.json, packages/@atjson/renderer-webcomponent/package.json, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-html/package.json, packages/@atjson/source-mobiledoc/package.json, packages/@atjson/source-prism/package.json, packages/@atjson/source-url/package.json
Some packages rely on new features in @atjson/document but their peer dependencies are out of date.
=> fix: update peer dependencies to @atjson/document

babel.config.js, package-lock.json, package.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/renderer-commonmark/test/commonmark-spec-test.ts, packages/@atjson/source-commonmark/src/source.ts, packages/@atjson/source-commonmark/test/extensions-test.ts, performance/index.ts, tsconfig.json
Swap put ts-jest in favor of babel-jest. This also updates the tsconfig to use esModuleInterop which works better with Babel.
=> chore: remove ts-jest and use babel-jest instead

packages/@atjson/source-html/src/parser.ts, packages/@atjson/source-html/test/source-html-test.ts
Parse annotation offsets were getting messed up when content had leading whitespace -- this fixes that by trimming html prior to parse
=> fix: leading whitespace trim

package.json
This copies files over to the npm package. It turns out that `tsc` doesn't copy over `.d.ts` files to its output 😭 , which means that we either need to:
1. Convert the type definition file to `.ts`
2. Copy the type definition over _manually_ after building the package.
We're doing the latter bc rewriting the interface to handle `class`es properly is pretty difficult to do correctly.
=> fix: add the CKEditor type definition to the npm module

lerna.json, package.json, packages/@atjson/renderer-commonmark/CHANGELOG.md, packages/@atjson/renderer-commonmark/package.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-gdocs-paste/CHANGELOG.md, packages/@atjson/source-gdocs-paste/package.json, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/test/converter-test.ts, packages/@atjson/source-gdocs-paste/test/fixtures/list-with-interrupting-paragraph.json
Switch the GDocs paragraph boundary sequence from two or more new lines
to a single new line character, and convert vertical tabs to linebreaks.
This is more consistent with GDocs formatting rules. Sequences of
multiple new line characters containing interstitial whitespace will be
collapsed into a single paragraph boundary.
Edit: this also adds support for pasting Lists with "interrupting paragraphs" which
can occur in GDocs (Ex https://docs.google.com/document/d/e/2PACX-1vRX6dmzmlW4NtjFj-KlXp3TGQTVyMBVBCVBwO4q9Bwwv8clmULhLmKjGxbz6Lf_qnLEQX9gewoAVJaz/pub)
In those cases we have text that is wrapped in a List but is not contained in any list
item. Because that text will always end in a newline which is now a paragraph separator,
that text will now be wrapped in a paragraph, producing …
=> fix: use single newline for gdocs paragraphs

packages/@atjson/renderer-react/src/index.ts
I was investigating an issue in Rocket using atjson and we were seeing this when trying to render `HorizontalRule` annotations into `hr` tags:
``Error: hr is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.``
I believe there may be a few forces at play here that create this issue in the particular implementation, as I'm unable to reproduce a test case that can create this error in the tests here, but that may be because the component structure is different enough that it's hard to force the same error.
Regardless, in looking at the renderer implementation, I realized we likely want to spread on the `children` argument to match the `createElement` implementation specified in the [React docs](https://reactjs.org/docs/react-api.html#createelement), so …
=> React-renderer: spread annotation children argument

packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/collection.ts, packages/@atjson/document/src/document.ts, packages/@atjson/document/src/utils.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/source-html/src/converter/video-embeds.ts
This will reduce calls to annotation.constructor, which had some wacky type coercion going on, and was a lookup that could be saved in many cases.
=> chore: store vendorPrefix on annotation instances

packages/@atjson/offset-annotations/src/annotations/video-embed.ts, packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts, packages/@atjson/source-html/src/converter/video-embeds.ts, packages/@atjson/source-html/test/converter-test.ts, packages/@atjson/source-url/src/converter.ts
Since atjson is already going through the trouble of normalizing these URLs and figuring out the providers, we wanted to take it a step further on consuming applications and add a `provider` attribute that will allow us to conditionally render based on the video provider. This is mostly relevant for AMP, where we need to use a different video component per provider source.
I'm assuming this should be considered a breaking change since downstream applications / converters / etc. will need to adjust any instance where they call `VideoURLs.identify`.
=> Add provider attribute to video embeds

package-lock.json, package.json, packages/@atjson/source-ckeditor/CHANGELOG.md, packages/@atjson/source-ckeditor/bin/index.ts, packages/@atjson/source-ckeditor/package.json, packages/@atjson/source-ckeditor/src/ckeditor.ts, packages/@atjson/source-ckeditor/src/source.ts, packages/@atjson/source-ckeditor/src/types/@ckeditor/ckeditor5-engine/index.d.ts, packages/@atjson/source-ckeditor/src/utils.ts, packages/@atjson/source-ckeditor/test/source-ckeditor-build-classic/source.ts, packages/@atjson/source-ckeditor/test/source-classic-build-editor-test.ts, website/docs/ckeditor-source.md
Update the CKEditor Source so we can `fromRaw` using a CK Document or DocumentFragment. We want to be able to do this because:
1.) We can generate a document fragment without using an instance of an Editor build
2.) We can generate a CKEditor Source document from a subtree of a model document (which we might need to do for captions, for example)
=> Source ck from document

packages/@atjson/document/src/document.ts, packages/@atjson/source-commonmark/test/commonmark-test.ts, packages/@atjson/source-html/test/source-html-test.ts
Sort annotations in a canonical document before deleting any text ranges, as that may cause annotations to collapse onto each other, at which point it is not possible to recover their sorting position in the original document.
We may later want to perform something more sophisticated to prevent the collapsing annotations altogether, such as selectively keeping some text that might lie under a parse annotation if it is necessary to preserve the order of other annotations in a document. Because even checking for that may be a large performance impact, we'd rather have Sources not create parse annotations like these in the first place, either in their `fromRaw` or `convertTo` steps, but this seems like a reasonable safeguard.
=> fix: preserve original document sort in canonical

packages/@atjson/document/src/collection.ts, packages/@atjson/document/test/atjson-test.ts, packages/@atjson/document/test/document-test.ts, packages/@atjson/document/test/test-source.ts, packages/@atjson/source-ckeditor/test/source-classic-build-editor-test.ts, packages/@atjson/source-ckeditor/test/source-classic-build-test.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-prism/test/__snapshots__/prism-test.ts.snap, packages/@atjson/source-prism/test/prism-test.ts, website/docs/ckeditor-source.md
Update the default sort function in @atjson/document `collection.compareAnnotations` to produce a sort order that maintains the hierarchical structure of the annotations. Given a hierarchical structure like
```
A
A1
A2
B
B1
B2
```
we'd like the comparison function to sort the annotations as `A, A1, A2, B, B1, B2`. To do this, we first sort by start position ascending, then end position descending, then rank ascending, and then by type ascending. This method of sorting was already independently implemented in source-ckeditor and source-gdocs-paste.
This sort still produces indeterminate results if two annotations of the same type are placed exactly at the same position - if we'd like to provide a consistent ordering in those situations, we could then sort on some hash value that takes into …
=> Default sort

packages/@atjson/document/src/document.ts, website/docs/document-api.mdx
Add an optional `filter` overload to `document.slice(start, end, filter?)` and `document.cut(start, end, filter?)`. The filter function allows us to override which annotations should be truncated and included in the slice or cut. By default, we had been truncating and including every annotation that overlaps the range. Sometimes, we may want to only include annotations that lie wholly within the range, such as when slicing/cutting a subdocument - in that case we (sometimes) do not want to include annotations that may be wrapping the subdocument's parent annotation:
```
<section><figure><figcaption>Here is a caption</figcaption></figure></section>
^--------------- caption ----------------^
^------------------------ figure -------------------------^
^------------------------------  section …
```
=> chore: add filter overload to doc.slice()

packages/@atjson/document/src/document.ts
Add the optional filter param to the ConversionDocument.slice() implementation.
=> fix: pass slice filter override in conversion docs

package-lock.json, package.json, packages/@atjson/source-wordpress-shortcode/.npmignore, packages/@atjson/source-wordpress-shortcode/.npmrc, packages/@atjson/source-wordpress-shortcode/CHANGELOG.md, packages/@atjson/source-wordpress-shortcode/README.md, packages/@atjson/source-wordpress-shortcode/package.json, packages/@atjson/source-wordpress-shortcode/src/annotations/index.ts, packages/@atjson/source-wordpress-shortcode/src/annotations/shortcode.ts, packages/@atjson/source-wordpress-shortcode/src/index.ts, packages/@atjson/source-wordpress-shortcode/src/source.ts, packages/@atjson/source-wordpress-shortcode/test/source-test.ts, packages/@atjson/source-wordpress-shortcode/tsconfig.json, packages/@atjson/source-wordpress-shortcode/tsconfig.modules.json, website/docs/wordpress-shortcode-source.mdx, website/sidebars.json
This source is designed to annotate WordPress shortcodes, allowing for content from WordPress to be converted into other formats. Since WordPress instances are highly customised, we don't provide any converters (currently) out of the box.
In the documentation site, I've provided an example of combining the WordPress shortcode source with the HTML source to get a fully annotated WordPress story.
=> Add WordPress shortcode source

renovate.json
This helps with upkeep in this repository by not having to merge lots of PRs
=> Automatically merge all renovate PRs except for major releases

packages/@atjson/offset-annotations/src/annotations/paragraph.ts, packages/@atjson/renderer-commonmark/src/index.ts
We want to support drop caps and stylistic lead ins in our text editor, and provide support that makes sense for both our text editor and our brand sites.
I've attached screenshots of what our editorial teams want (for _The New Yorker_ and _WIRED_ respectively).
These will be implemented by adding a decoration to paragraphs. I'm choosing to make these arrays to allow for multiple decorations, since I've seen publications like _The Atlantic_ use both together effectively:
=> Add decorations as an optional attribute on paragraphs

packages/@atjson/source-html/src/converter/index.ts, packages/@atjson/source-html/test/converter-test.ts
This was something missed in our conversion rules— this adds support for converting titles into annotations.
=> Convert link "title" attributes from HTML

packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts, packages/@atjson/source-url/test/url-test.ts
This fixes YouTube videos that weren't retaining start times when being embedded through URL paste.
=> Fix YouTube videos that start at an offset

packages/@atjson/offset-annotations/src/annotations/blockquote.ts, packages/@atjson/offset-annotations/src/annotations/heading.ts, packages/@atjson/offset-annotations/src/annotations/paragraph.ts, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/renderer-test.ts, packages/@atjson/source-gdocs-paste/src/annotations/alignment.ts, packages/@atjson/source-gdocs-paste/src/annotations/heading.ts, packages/@atjson/source-gdocs-paste/src/annotations/index.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/src/paragraph-styles.ts, packages/@atjson/source-gdocs-paste/src/source.ts, packages/@atjson/source-gdocs-paste/test/fixtures/heading-alignment.json, packages/@atjson/source-gdocs-paste/test/fixtures/paragraph-alignment.json, packages/@atjson/source-gdocs-paste/test/fixtures/rtl-paragraph-alignment.json, packages/@atjson/source-gdocs-paste/test/text-alignment-test.ts, packages/@atjson/source-html/src/converter/headings.ts, packages/@atjson/source-html/src/converter/index.ts, packages/@atjson/source-html/src/converter/paragraphs.ts, packages/@atjson/source-html/src/converter/utils.ts, packages/@atjson/source-html/test/heading-test.ts, packages/@atjson/source-html/test/paragraph-test.ts, packages/@atjson/source-prism/test/__snapshots__/prism-test.ts.snap, tests/fixtures/html/paragraph.html, website/docs/google-docs-explainer.md
This adds support for text alignment, based off of new experimental CSS properties that are language independent, `start`, `end`, `center`, and `justify`.
I've added support for Google Docs and HTML parsing to automatically apply these styles to Paragraphs and Headings.
One note to do here is that we're missing language codes on subsections of the document / the whole atjson document, which may be important to correctly render out these properties of `start` / `end` to the correct values for that language.
=> Add support for text alignment

packages/@atjson/renderer-plain-text/package.json, packages/@atjson/renderer-plain-text/src/index.ts, packages/@atjson/renderer-plain-text/test/text-renderer-test.ts
For prettier formatting of lists, we'd like to add line breaks when rendering lists to plain text
=> Add line breaks in plain text renderer

packages/@atjson/offset-annotations/src/annotations/list.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/__snapshots__/commonmark-spec-test.ts.snap, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/renderer-test.ts, packages/@atjson/source-commonmark/src/annotations/bullet_list.ts, packages/@atjson/source-commonmark/src/annotations/ordered_list.ts, packages/@atjson/source-commonmark/src/converter.ts, packages/@atjson/source-commonmark/src/parser.ts, packages/@atjson/source-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/test/utils.ts
This changes defaults when creating `List` annotations without a tight attribute and will make all lists without this attribute tight by default. We're making this change to match editor expectations when writing in rich text, which we use this library for. Our editors at WIRED and Vanity Fair would like their lists to be compact by default. Our previous data structuring made everything loose by default and tight explicitly. By inverting this and making the attribute that needs to be set `loose`, we make tight lists the default and loose lists explicit.
To illustrate, the difference between tight and loose lists can be shown below:
###
**Tight lists** (now default)
```md
- one fish
- two fish
- red fish
- blue fish
```
- one fish
- two fish
- red fish
- blue fish
###
**Loose lists** …
=> Change tight attribute to loose on lists

packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts, packages/@atjson/source-html/test/converter-test.ts
This adds support for detecting Twitch streams and turning them into iframes. For anyone who would like to use Twitch embeds in their application, they will need to manually handle the `parent` query parameter that is required by Twitch, since there's no mechanism for environment variables (nor is there a strong need for them).
=> Add support for Twitch embed recognition

package-lock.json, packages/@atjson/offset-annotations/src/utils/video-urls.ts, packages/@atjson/offset-annotations/test/video-canonicalisation-test.ts
When canonicalizing Twitch URLs, preserve the `parent` parameter if it
is already set
=> Fix twitch urls

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/offset-annotations/test/social-urls-test.ts
Older Spotify embeds use a query param of `uri`, specifying a Spotify URI that corresponds to the embed type and ID. This adds support to the Spotify normalizer for this structure of embed.
=> fix(spotify-embeds): Parse Spotify uri-based embeds

packages/@atjson/offset-annotations/src/annotations/link.ts
With this PR, I have added a new `linkStyle` attribute to the `Link` annotation which helps to render a link as a button or other styles (Button with icon, Link with icon etc) in consumer applications. As of now, this `Link` annotation can be used as inline anchor tag in paragraph. 
By adding this new attribute, it helps, if we want to use this anchor tag between the paragraph (see screenshot below) and need to provide any style type according to the render style in consumer applications.
nb. Edited to remove links to private documentation by @tim-evans
=> feat(link): link style attribute

packages/@atjson/offset-annotations/src/annotations/index.ts, packages/@atjson/offset-annotations/src/annotations/telegram-embed.ts, packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/offset-annotations/test/social-urls-test.ts
Add support for Telegram embeds, which is currently used by Russian markets.
=> feat(telegram-embed): Add Telegram urls recognition

package-lock.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/escaped-text-test.ts
While testing some markdown <-> rich text editing, I noticed that we had a review of an album, [>>](https://pitchfork.com/reviews/albums/16697-recordreview/) by Beak>. This adds tests and correct escape sequences for text that starts with `>`
=> Escape blockquote characters

packages/@atjson/document/src/index.ts, packages/@atjson/document/tsconfig.modules.json
This allows atjson to be used by [vite](https://vitejs.dev) in development mode; this requires `isolatedModules` mode to be set to `true`, which caused some changes in the exports for the `index.ts` file.
=> Add support for isolated modules for running atjson using vite

packages/@atjson/offset-annotations/src/annotations/firework-embed.ts
Related PR: https://github.com/CondeNast/atjson/pull/1262
Added a `channel` param to the embed and renamed existing to "url" and "open" instead of "playlist" and "openIn", the new embed should be:
[#firework: url channel:value open:value]
=> feat: add channel param to firework embed

packages/@atjson/offset-annotations/src/annotations/firework-embed.ts
Related PR: https://github.com/CondeNast/atjson/pull/1265
Changed `channel` param type from "string" to `string`.
=> fix: change channel param type to string

packages/@atjson/offset-annotations/src/annotations/firework-embed.ts
Related PR: https://github.com/CondeNast/atjson/pull/1268
Renamed `url` attribute into `id` to reconciliate info accordingly to the embed code that should be:
[#firework: id channel:value open:value]
An example:
[#firework XXXXX channel:voguemagazine open:_modal]
=> fix: rename url field into id to reconciliate definitions

packages/@atjson/offset-annotations/src/utils/aspect-ratios.ts, packages/@atjson/offset-annotations/test/aspect-ratio-test.ts
Some data formats have difficulty with decimal-valued aspect
ratios, so this PR replaces these with their whole-number
equivalent:
1.85:1 -> 37:20
1.9:1 -> 19:10
2.2:1 -> 11:5
2.4:1 -> 12:5
3.6:1 -> 18:5
=> chore: use whole-number aspect ratios

.husky/commit-msg, .husky/pre-commit, package-lock.json, packages/@atjson/document/src/annotation.ts, packages/@atjson/document/src/annotations/index.ts, packages/@atjson/document/src/annotations/slice.ts, packages/@atjson/document/src/document.ts, packages/@atjson/document/src/index.ts, packages/@atjson/hir/src/hir.ts, packages/@atjson/offset-annotations/src/annotations/iframe-embed.ts, packages/@atjson/offset-annotations/src/annotations/video-embed.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts, packages/@atjson/renderer-plain-text/src/index.ts, packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer-test.tsx, packages/@atjson/source-commonmark/test/utils.ts, packages/@atjson/source-html/src/converter/video-embeds.ts, packages/@atjson/source-html/test/converter-test.ts, website/docs/react-renderer.mdx
This has been something that has come out of a bunch of experimentation, with a driving factor being a short talk I gave at [have you tried to rub a database on it?](https://www.hytradboi.com/). The code I wrote for this talk was taking wikitext, a well known and sort of esoteric format, and providing normalization via atjson. During the process of writing the code, I found that it was very difficult to have relational thinking of data using the subdocument model, and found myself creating a new primitive in atjson using slices as the base concept.
It has worked very well in some real applications where I've done testing and would like to propose that we deprecate subdocuments in favor of this new primitive. For an example of this in code, you can take a look at the [code for the …
=> Introducing slices

packages/@atjson/hir/src/hir.ts, packages/@atjson/renderer-commonmark/test/slice-test.ts, packages/@atjson/renderer-hir/src/index.ts
This fixes a bug with the commonmark renderer that was incorrectly looking at outdated text and inferring incorrect behavior. By passing the altered document down from the hir to the renderer, we have similar behavior prior to introducing slices (it should be similar to subdocuments).
This is causing issues upstream with the contrived test I've included. Prior to this change, it would mess up the italics and mangle the document:
```md
And an [*emphasized link](https://www.bonappetit.com*)
```
When it should correctly place the emphasis marks outside the link:
```md
And an *[emphasized link](https://www.bonappetit.com)*
```
=> Pass altered document to hir-renderer

packages/@atjson/hir/src/hir.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts, packages/@atjson/renderer-react/src/index.ts
This is the same category of bug as #1307, where the document being passed along to the context object was pointing to an out of date (and in this case, completely incorrect document). This caused context specific errors with subclasses of the commonmark renderer, as it uses the document to do backtracking to automatically correct categories of errors that may be produced by using a rich text editor to write markdown.
=> Fix slice document context

packages/@atjson/hir/src/hir.ts, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts, packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer-test.tsx
Some code reviews and discussions have brought up that there's quite a bit of magic going on with slices. To address this, I have a suggestion for an approach that is considerably less magical and requires more explicit interventions to get it working.
tldr;
I've added a function called `slice` on the `renderer-hir` which will return the slice document for that id. If none is returned, it's up to the client to figure out what to do. Previously, this would be handled behind the scenes. To preemptively address some annoying developer experience, I've made renderers accept `null` documents, which will return nothing. This makes code a bit easier to read, since you can do some nullish coalescing to resolve in these cases.
For `renderer-react`, I've introduced a new component called `Slice`, …
=> Stop reifying slices in renderers

packages/@atjson/document/src/annotations/slice.ts, packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/__snapshots__/with-stable-ids-test.ts.snap, packages/@atjson/document/test/serialize-test.ts, packages/@atjson/hir/src/hir-node.ts, packages/@atjson/offset-annotations/src/annotations/iframe-embed.ts, packages/@atjson/offset-annotations/src/annotations/video-embed.ts, packages/@atjson/renderer-react/src/index.ts, packages/@atjson/renderer-react/test/react-renderer-test.tsx, packages/@atjson/source-commonmark/test/commonmark-test.ts, packages/@atjson/source-html/src/converter/index.ts, packages/@atjson/source-html/src/converter/video-embeds.ts, packages/@atjson/source-html/test/blockquote-test.ts, packages/@atjson/source-html/test/converter-test.ts, packages/@atjson/source-html/test/source-html-test.ts, packages/@atjson/source-mobiledoc/src/parser.ts, packages/@atjson/source-mobiledoc/test/source-mobiledoc-test.ts, packages/@atjson/source-prism/test/__snapshots__/prism-test.ts.snap, packages/@atjson/source-prism/test/prism-test.ts, packages/@atjson/source-url/src/converter.ts, packages/@atjson/source-url/test/url-test.ts
This adds a guard to ensure that `\uFFFC` isn't in the resulting serialized text and updates tests that were previously using the HIR to test for correct structure to instead use `serialize`.
=> Guard against object replacement characters

packages/@atjson/offset-annotations/src/annotations/ceros-embed.ts, packages/@atjson/offset-annotations/src/annotations/firework-embed.ts, packages/@atjson/offset-annotations/src/annotations/horizontal-rule.ts, packages/@atjson/source-html/test/converter-test.ts
After re-evaluating some types using the new serialization format, it's clear that these should be blocks and not objects.
We expect a horizontal rule to be _between_ paragraphs. I understand that `hr` is confusingly self closing, but it also doesn't have the "self-closing" properties that the peritext format we're adopting has. It always between blocks, which makes it a block, imo
=> fix: change types for ceros-embed / firework-embed / horizontal-rule from object to block

packages/@atjson/source-html/src/converter/third-party-embeds.ts
This was causing failures when running performance checks.
=> fix: new URL for Ceros detection was not in try / catch

package-lock.json, packages/@atjson/document/src/index.ts, packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize-test.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/renderer-commonmark/test/slice-test.ts, packages/@atjson/renderer-hir/package.json, packages/@atjson/renderer-hir/src/index.ts, packages/@atjson/renderer-hir/test/renderer-hir-test.ts, packages/@atjson/renderer-hir/tsconfig.json, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/renderer-test.ts, packages/@atjson/renderer-plain-text/test/text-renderer-test.ts
Effectively deprecates using `@atjson/hir` by replacing internal calling functions to use `@atjson/util` instead.
New things:
- `Mark<T>` and `Block<T>` are exported from `@atjson/document` which allow for developers to get the proper JSON from a mark or block given an annotation. (It's kind of similar to `PropsOf<T>`).
- On serialization, there's an option to throw errors or warn when encountering unknown annotations. This behavior is set to `throw` in rendering, and can be overridden as-needed.
- `@atjson/renderer-hir` uses `@atjson/util` internally and has two high level functions called `renderBlock` and `renderMark`, which act very simlarly to `renderAnnotation`.
- `@atjson/renderer-commonmark` will produce slightly different HTML than previous (ordering of bold / italic _will not_ …
=> Use util instead of hir

packages/@atjson/util/src/index.ts, packages/@atjson/util/test/extract-slices-test.ts
This fixes an issue with multiple blocks in slices that cause blocks to be stripped due to invalid nesting.
(The bug here was `blocks[0]`, since we _always_ make the blocks `[]` for the first item... oops!)
=> fix: handle multiple blocks in slices correctly

packages/@atjson/renderer-commonmark/src/index.ts
We were passing attributes by reference down to renderers, which we previously weren't. Instead of cloning the attributes, I'm instead opting to change rendering to not mutate attributes, since it caused a significant performance hit.
=> Don't mutate attributes in renderers

.github/workflows/docs.yml, .github/workflows/perf.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
This adds two pipelines for releasing atjson (by prerelease and release) so developers can self-manage releases automatically via github's UI. Both prereleases and releases have blockers on them, which require an approval by any developer at Condé right now.
=> Setup publishing to happen via github actions

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
For a _very_ specific case, we need to invert the nesting of bold and italic, since markdown can't handle four / five star delimiter runs when parsing.
Previously, we were producing invalid markdown that looked like the following:
> ```md
> ***Space*****: the final frontier**
> ```
> 
> ***Space*****: the final frontier**
The five star run is invalid, and using a naïve approach, we could adjust this so we fix the italic mark to render as an underscore, which would produce:
> ```md
> **_Space_****: the final frontier**
> ```
> 
> **_Space_****: the final frontier**
But this is also an invalid delimiter run!
We have to re-orient the bold and italic marks in the tree to create the following markdown, which is the only valid structure:
> ```md
> *__Space__***: the final frontier**
> ```
>
> …
=> fix: handle four and five star formatting of markdown

package-lock.json, package.json, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark-spec-test.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts, packages/@atjson/source-commonmark/package.json, packages/@atjson/source-commonmark/src/converter.ts, packages/@atjson/source-commonmark/src/parser.ts
This updates markdown-it to 13.0.1 (the most recent version of markdown-it) along with a change to entities to match the version specified. This contains some fixes which can be checked in https://github.com/CondeNast/atjson/pull/1319
=> feat: update markdown-it

packages/@atjson/source-commonmark/src/parser.ts, packages/@atjson/source-commonmark/test/extensions-test.ts
Remove half of the parse tokens generated by the parser, reducing the size of `N` in `O(N)` by a 1/3.
The math for this is:
- 1 starting `+uFFFC` token and a parse token
- the markdown token
- 1 ending `+uFFFC` token and a parse token
So, from the following markdown, `**hello, world**`, we create: `+uFFFChello, world+uFFFC`. This pull request changes this to be `+uFFFChello, world`.
=> chore: remove half the parse tokens from source-commonmark

packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize-test.ts
Fix a bug where we were sorting the MARK_END token before the MARK_START token for zero-length marks. In the case we have:
* two tokens with the same index
* and the same annotation ID we assume that one of them is the start and the other is the end token. If the first is the start token, return -1 in the comparator to sort it first
=> fix: sorting start/end tokens for zero-length marks

packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize-test.ts, packages/@atjson/source-gdocs-paste/src/converter.ts, packages/@atjson/source-gdocs-paste/test/converter-test.ts
Fix an issue where under certain circumstances we were producing
malformed ranges for 0-length marks. This would happen if the
MARK_END token was sorted before the MARK_START token for that
annotation, which could only happen for 0-length marks that
coincided with a PARSE_END and/or BLOCK_START. Even in that case,
the error depended on the way the list of tokens was divided and
merged during the internals of the sorting algorithm.
The fix here sidesteps the issue by replacing the MARK_START and
MARK_END tokens with a single MARK_COLLAPSED token in this case.
The mark range can be easily computed from the token since we know
that it is collapsed.
With this fix in the serialize function, we no longer need
to remove 0-length marks during the GDocs paste conversion, since these
no longer …
=> fix: add MARK_COLLAPSED token to document serialize

packages/@atjson/source-html/src/converter/third-party-embeds.ts, packages/@atjson/source-html/test/firework-embed-test.ts
Firework embed codes from their CMS has newlines between the script tag and web component. This results in an unintentional newline being added to the text when pasted in to a document.
=> fix: strip newline when converting firework embed codes

packages/@atjson/source-gdocs-paste/src/converter.ts, website/src/components/GDocsPasteDemo.tsx
This adjusts whitespace from Google Docs paste so when rendering to HTML, marks are sticky to text instead of wrapping around whitespace (which happens fairly often due to imprecise UI in Google Docs)
=> fix: normalize mark boundaries from google docs paste

packages/@atjson/source-gdocs-paste/src/converter.ts
Pasted content from GDocs may contain a number of zero-width marks. When these appeared at the beginning of the content, we'd hit a bug when trying to adjust the marks for whitespace.
=> fix: handle zero-width marks when adjusting for whitespace

packages/@atjson/source-html/src/annotations/firework-embed.ts, packages/@atjson/source-html/test/firework-embed-test.ts
We need to update the parameters of the firework embed to allow for captions="false"
The current firework embed that is pasted into copilot looks like this:
```
<fw-embed-feed
channel="voguemagazine" 
playlist="gp7a2o"
mode="row"
open_in="default"
max_videos="0"
placement="middle"
player_placement="bottom-right">
</fw-embed-feed>
```
We need to add the captions parameter to the accepted params in the Copilot UI.
AC:
captions=”false” is added to the accepted params for the firework embed in Copilot
=> chore: add captions to firework embed

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/adjacent-inline-test.ts, packages/@atjson/renderer-commonmark/test/commonmark-test.ts
Add tests for issues with markdown rendering with certain arrangements of bold/italic. Some of these cases can arise somewhat naturally in HTML-like documents.
The markdown produced from the failing tests includes invalid delimiter runs where the delimiter characters would appear in the parsed md output
=> chore: add failing tests for continued marks

.github/workflows/prerelease.yml
This fixes an error encountered in [this run](https://github.com/CondeNast/atjson/actions/runs/5601397804) of the prerelease action, which failed to comment the published revision not due to failing to publish, but due to not being able to store the JSON to $GITHUB_OUTPUT. Instead of pushing the data to the github output, I'm having the next step read from the file written with the lerna summary results directly
=> fix: update prerelease script to not have EOF errors when sharing output over steps

packages/@atjson/source-html/src/converter/index.ts, packages/@atjson/source-html/test/converter.test.ts
Update our html-source to convert the `sandbox` attribute for iframe elements. 
This attribute is already supported in the iframe-embed annotation in the offset-annotations source
=> chore: convert iframe `sandbox` attr

packages/@atjson/source-html/src/converter/index.ts, packages/@atjson/source-html/test/converter.test.ts
The `sandbox` attribute on an `<iframe>` element will be space- delimited, but our convention is to have this be comma-delimited on the IframeEmbed annotation
=> fix: convert space to commas in sandbox attr

packages/@atjson/react/src/components/Node.ts, packages/@atjson/react/src/components/Slice.ts, packages/@atjson/react/src/index.ts, packages/@atjson/react/test/children.test.tsx, packages/@atjson/react/test/slice.test.tsx
While playing with this library, I noticed that `Children.map` was returning a single node instead of N nodes, which makes it harder to encapsulate higher order behaviors in things like groups.
=> fix(react): rearchitect Node so Children.map can be used by consumers

packages/@atjson/util/src/index.ts, packages/@atjson/util/test/extract-slices.test.ts
This is a bug that I discovered with @colin-alexa during work on datasets & tables. Our current implementation of `extractSlices` does not properly handle overlapping slices, and will duplicate text since it does not handle cases where slices are nested or overlap.
To illustrate this, we may have a document that has slices inside of slices, which are 
something _very_ possible inside of tables:
| Album Art |  Info |
|-----------|-------|
| <figure><img src="https://f4.bcbits.com/img/a2682265154_10.jpg" width=200><figcaption>Debut (1993)<br/><a href="https://bjork.bandcamp.com/album/debut">Listen on Bandcamp</a></figcaption></figure> | <p>Debut is the debut studio album by Icelandic recording artist Björk as an international singer, released in July 1993 by One Little Independent Records …
=> fix: handle overlapping slices

packages/@atjson/util/src/index.ts, packages/@atjson/util/test/extract-slices.test.ts
A bug in the sorting function used internally by the `extractSlices` util caused cascading errors in the logic of the function, eventually causing the renderer for tables in markdown and html to duplicate the contents of some cells into their neighbors.
While fixing this bug, I also added some documentary comments to explain the logic and behavior of this sorting function, along with tests that show real data that was affected by the bug in `extractSlices` as well as specific abstracted test cases for the problematic sorting logic.
=> fix: bug in extractSlices sorting function caused weird behavior with some table and dataset documents

packages/@atjson/document/src/change.ts, packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize.test.ts, packages/@atjson/offset-annotations/src/utils/convert-html-tables.ts, packages/@atjson/source-commonmark/test/__snapshots__/extensions.test.ts.snap, packages/@atjson/source-html/test/__snapshots__/table.test.ts.snap
There's a bug in the `serialize` function that causes collapsed blocks to end up occasionally consuming the entire remainder of the document due to their start and ends being reversed by the token sorting algorithm.
I added some (skipped) tests to demonstrate the problem, and changed the conversion code for tables and datasets to avoid generating problematic documents.
For future reference, the issue is fundamental to the sorting process for our tokens. start and end tokens are usually sorted end -> start, but when they belong to the same annotation they're sorted start -> end; this produces a logical contradiction that no generic nlogn sort algorithm can deal with (the comparison function is *intransitive*, so comparing A to B and B to C doesn't let you infer how A relates to C).
Fixing …
=> fix: don't produce collapsed dataset annotations in converter

packages/@atjson/offset-annotations/src/utils/convert-html-tables.ts, packages/@atjson/source-commonmark/test/__snapshots__/extensions.test.ts.snap, packages/@atjson/source-commonmark/test/extensions.test.ts, packages/@atjson/source-html/test/__snapshots__/table.test.ts.snap
There's an issue with the `insertText` method that makes it difficult to insert an object (that is, a new annotation wrapping a single `\uFFFC` character) at a position where two annotations meet, such that the new text and annotation ends up *between* the two existing annotations. That's something we will need to fix, but to sidestep the problem it's easy to just change how we're doing datasets
=> fix: wrap dataset annotation around tables during conversion

packages/@atjson/offset-annotations/src/annotations/bluesky-embed.ts, packages/@atjson/offset-annotations/src/annotations/index.ts, packages/@atjson/offset-annotations/src/index.ts, packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/bluesky-embed.test.ts, packages/@atjson/source-html/src/converter/social-embeds.ts, packages/@atjson/source-html/test/bluesky-embed.test.ts
Adds support for detecting and rendering Bluesky posts from HTML. Bluesky's at protocol uses IPFS addressing to identify content, so we need to include both a `uri`, and a `cid`, which is the IPFS content id. A `url` is also included so we have a permalink to the post in the case that the post cannot be shown due to user consent not being provided.
```html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:xrr5j2okn7ew2zvcwsxus3gb/app.bsky.feed.post/3kshwuxmy5o2y" data-bluesky-cid="bafyreicg7axsdp6b7f4uj75ggdfhrdl52cqpjah45scox3prmqflwg557i"><p lang="en">Lap time al fresco. Photo from my collection, no date/info.<br><br><a href="https://bsky.app/profile/did:plc:xrr5j2okn7ew2zvcwsxus3gb/post/3kshwuxmy5o2y?ref_src=embed">[image or embed]</a></p>&mdash; Cats of Yore (<a …
```
=> BlueskyEmbed

packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize.test.ts
When text blocks are added manually, this would previously eat some text that was sliced out. We didn't see this in any code until changes were made for Reddit Embeds and other embed types that had inline textual content.
=> fix: use text annotations in serialization

packages/@atjson/source-html/src/converter/social-embeds.ts, packages/@atjson/source-html/test/instagram-embed.test.ts
Add support for setting the `hidePostCaption` attribute from the instagram embed code in the source-html converter.
This is supported in our annotations but wasn't being set when converting from an embed code
=> chore: convert hidePostCaption from insta embed code

packages/@atjson/source-commonmark/src/converter/index.ts, packages/@atjson/source-commonmark/test/extensions.test.ts
Some of the logic we recently introduced around table headers isn't really general-purpose; the decision to equate "markdown table with no text in header cells" with "html table with no thead section" is a particular decision for our own technologies, and makes more sense to implement in a private package rather than the public atjson repo
=> fix: handle empty markdown table headers in proprietary packages

packages/@atjson/offset-annotations/src/annotations/image.ts, packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/commonmark.test.ts, packages/@atjson/source-commonmark/src/converter/image.ts, packages/@atjson/source-commonmark/src/converter/index.ts, packages/@atjson/source-commonmark/test/extensions.test.ts
Add optional link attributes to the offset Image annotation
Update the Commonmark source to set the link attribute on Image
annotations if there is a link that wraps an image only.
Update the Commonmark renderer to render a md link around an image
if the link attribute is set
=> feat: explicit Link attributes for images

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-html/src/index.ts
This PR addresses an issue where tables are not being rendered inside an accordion.
When table is placed inside another block type like an accordion, The table block id will be a concatenation of "parent/accordion block id + table data set id" so the check is being converted from "===" to "includes"
=> fix: accordion tables copilot-12204

packages/@atjson/react/src/contexts/DataSet.ts, packages/@atjson/react/src/hooks/useDataSet.ts, packages/@atjson/react/src/index.ts, packages/@atjson/react/test/data-set.test.tsx
adds a hook to the @atjson/react renderer package that allows components to access datasets (by id) on the current document while rendering. Something like this is necessary to support tables and other dataset visualization objects
=> feat: useDataSet hook in the react renderer

packages/@atjson/renderer-html/src/index.ts, packages/@atjson/renderer-html/test/encoding.test.ts
Use the UTF8 encoding mode when encoding entities in the HTML renderer. This things like Japanese characters won't be encoded but reserved HTML characters like <, >, & will still be
=> chore: use utf8 charset when encoding entities

packages/@atjson/document/src/join.ts
small bugfix for the Join API so that the arguments to Join.join can be cast to their correct annotation subtypes
=> fix: type of Join.join arg to Annotation<any>

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/perf.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
Github has deprecated upload-artifact@v3. This updates our github actions dependencies to the most recent versions of each of them.
=> chore: update actions to most recent versions

packages/@atjson/renderer-commonmark/src/index.ts, packages/@atjson/renderer-commonmark/test/escaped-text.test.ts
We previously did this for examples like
```
1. some text 
```
where we had text following the numbered list, but were not doing so for cases like
```
1.
```
where the end-of-line occurred right after the period
=> fix: escape text that looks like numbered lists

packages/@atjson/offset-annotations/src/utils/social-urls.ts, packages/@atjson/offset-annotations/test/social-urls.test.ts, packages/@atjson/source-html/src/converter/social-embeds.ts, packages/@atjson/source-html/test/threads-embed.test.ts
Update our SocialURLs util to identify threads.com URLs, where we previously only supported threads.net
=> fix: identify threads.com and threads.net social urls

packages/@atjson/document/src/serialize.ts, packages/@atjson/document/test/serialize.test.ts
This adds an option to include parse tokens in serialization to Peritext, which is helpful in cases where someone wants to view source of a document in a case like viewing the HTML tokens of the document, while allowing for text highlighting. The feature is also useful for debugging cases where you may want to see if some data is getting truncated unintentionally.
A feature like this was used for the hytradboi talk I did on wikitext parsing. In trying to ensure that everything is working well on `main` with the quite extensive changes in the last year, I'm trying to update that project to see if there are any issues with the new format :)
Regardless of this feature, the changes to the `sortTokens` function may improve performance in some cases and be more legible for other developers
=> feat: add option to include parse tokens in serialize
